### ISSUE TITLE
Error pops up, possibly from teleporting around and what not

### ISSUE THREAD

**Issue by Yovez** [Skoice/skoice#47]
From what I can tell it seems to mainly happen when teleporting, like /home, or dying and going back to spawn or the set home.

```java
[00:05:25 ERROR]: [net.clementraynaud.skoice.dependencies.jda.api.JDA] One of the EventListeners had an uncaught exception
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "net.clementraynaud.skoice.system.Network.getChannel()" is null
at net.clementraynaud.skoice.listeners.guild.voice.GuildVoiceMoveListener.lambda$onGuildVoiceMove$2(GuildVoiceMoveListener.java:67) ~[Skoice.jar:?]
at java.util.stream.MatchOps$1MatchSink.accept(Unknown Source) ~[?:?]
at java.util.concurrent.ConcurrentHashMap$KeySpliterator.tryAdvance(Unknown Source) ~[?:?]
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:?]
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) ~[?:?]
at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
at java.util.stream.ReferencePipeline.noneMatch(Unknown Source) ~[?:?]
at net.clementraynaud.skoice.listeners.guild.voice.GuildVoiceMoveListener.onGuildVoiceMove(GuildVoiceMoveListener.java:67) ~[Skoice.jar:?]
at net.clementraynaud.skoice.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:382) ~[Skoice.jar:?]
at net.clementraynaud.skoice.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[Skoice.jar:?]
at net.clementraynaud.skoice.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[Skoice.jar:?]
at net.clementraynaud.skoice.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[Skoice.jar:?]
at net.clementraynaud.skoice.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:170) ~[Skoice.jar:?]
at net.clementraynaud.skoice.dependencies.jda.internal.handle.VoiceStateUpdateHandler.handleGuildVoiceState(VoiceStateUpdateHandler.java:223) ~[Skoice.jar:?]
at net.clementraynaud.skoice.dependencies.jda.internal.handle.VoiceStateUpdateHandler.handleInternally(VoiceStateUpdateHandler.java:58) ~[Skoice.jar:?]
at net.clementraynaud.skoice.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[Skoice.jar:?]
at net.clementraynaud.skoice.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:953) ~[Skoice.jar:?]
at net.clementraynaud.skoice.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:840) ~[Skoice.jar:?]
at net.clementraynaud.skoice.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:818) ~[Skoice.jar:?]
at net.clementraynaud.skoice.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:992) ~[Skoice.jar:?]
at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[Skoice.jar:?]
at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[Skoice.jar:?]
at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[Skoice.jar:?]
at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[Skoice.jar:?]
at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[Skoice.jar:?]
at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[Skoice.jar:?]
at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[Skoice.jar:?]
```

**Comment by LucasCdry** [comment]
Hey! Thanks for the report. This error should no longer show up in the latest version of Skoice (3.1).
